### ISSUE TITLE
`whitesource run` task failing

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/next-article#1311]
With a rather esoteric error

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/node_modules/readdirp/node_modules/readable-stream/dependencies/inline-process-browser/dependencies/through2/dependencies/readable-stream/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at WsNodeReportBuilder.traverseShrinkWrapJson (/home/ubuntu/next-article/node_modules/whitesource/bin/ws_node_report_builder.js:127:36)
    at buildReport (/home/ubuntu/next-article/node_modules/whitesource/bin/whitesource.js:58:48)
    at /home/ubuntu/next-article/node_modules/whitesource/bin/whitesource.js:93:16
    at /home/ubuntu/next-article/node_modules/whitesource/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
```

e.g. https://circleci.com/gh/Financial-Times/next-stream-page/2287

**Comment by i-like-robots** [comment]
Holy moly that's a deep dependency tree, Batman!

**Comment by andygnewman** [comment]
Have raised it with Whitesource.

**Comment by andygnewman** [comment]
Will close this. Seems to have mysteriously resolved it self.
